FROM node:18-bullseye

# Define una variable de entorno para el puerto
ENV PORT=5020

# Establece el directorio de trabajo
WORKDIR /app

# Copia el contenido del directorio actual al directorio de trabajo
COPY . .

# Instala las dependencias
RUN npm install

# Exponer el puerto
EXPOSE $PORT
EXPOSE $NODE_SERVICE_IP

# Establece el comando predeterminado para iniciar la aplicación
CMD ["npm", "start"]
